import numpy as np

In [3]:
simple_list=[6,7,9]
np.array(simple_list)

array([6, 7, 9])

In [6]:
arr=np.array([1,2,3])
arr

array([1, 2, 3])

In [5]:
list_of_lists=[([1,2,3],[4,5,6],[7,8,9])]
np.array(list_of_lists)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [7]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [8]:
np.arange(1,100)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [9]:
np.arange(1,31,5)

array([ 1,  6, 11, 16, 21, 26])

In [10]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [11]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros(10,int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [14]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.ones(100)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [16]:
np.ones(10,int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [17]:
np.zeros((2,5),int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [18]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [19]:
np.linspace(0,20,8)

array([ 0.        ,  2.85714286,  5.71428571,  8.57142857, 11.42857143,
       14.28571429, 17.14285714, 20.        ])

In [20]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(3,5)

array([[0.41315899, 0.63093444, 0.58761634, 0.39599677, 0.7270215 ],
       [0.27240333, 0.59351198, 0.52746894, 0.19669448, 0.20793257],
       [0.23921891, 0.70808781, 0.00094284, 0.51648802, 0.09707282]])

In [22]:
arr=np.random.randn(2,4)
arr

array([[ 0.07795275, -0.08380586,  0.66722897, -0.6587269 ],
       [ 0.21325254,  1.41852017,  0.36006683, -1.43090942]])

In [23]:
np.random.randint(2,100)

37

In [3]:
np.random.randint(20,56,100)

array([49, 54, 44, 54, 33, 21, 31, 36, 26, 31, 29, 53, 47, 44, 48, 43, 50,
       34, 42, 45, 41, 50, 55, 44, 29, 37, 33, 46, 21, 32, 48, 39, 44, 27,
       33, 29, 35, 33, 31, 24, 22, 20, 30, 34, 24, 24, 49, 31, 36, 52, 28,
       39, 20, 36, 24, 48, 28, 49, 32, 27, 34, 43, 55, 25, 30, 23, 55, 52,
       37, 43, 29, 45, 47, 35, 46, 33, 35, 33, 28, 47, 30, 23, 52, 31, 43,
       51, 35, 23, 49, 39, 37, 36, 39, 36, 50, 38, 43, 45, 34, 46])

In [5]:
sample_array=np.arange(30)
sample_array

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]


In [24]:
rand_array=np.random.randint(0,100,20)
rand_array

array([71, 95, 22, 48, 25, 94, 99, 16,  5, 32, 47, 95, 46, 93, 88, 43, 99,
       18,  7, 91])

In [8]:
sample_array.reshape(5,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [9]:
sample_array.reshape(4,3)

ValueError: cannot reshape array of size 30 into shape (4,3)

In [25]:
rand_array.max()

99

In [26]:
rand_array.argmax()

6

In [31]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a=np.random.rand(2,3)
a

array([[0.29715829, 0.42709364, 0.39371545],
       [0.30995621, 0.40291211, 0.24911837]])

In [28]:
a.T

array([[0.29715829, 0.30995621],
       [0.42709364, 0.40291211],
       [0.39371545, 0.24911837]])

In [29]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [30]:
sample_array[0]

10

In [14]:
sample_array[2:5]

array([2, 3, 4])

In [32]:
sample_array[1:4]=100
sample_array

array([ 10, 100, 100, 100,  14,  15,  16,  17,  18,  19,  20])

In [33]:
sample_array=np.arange(10,21)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [19]:
sample_array[0:7]

array([10, 11, 12, 13, 14, 15, 16])

In [34]:
subset_sample_array=sample_array[0:7]
subset_sample_array

array([10, 11, 12, 13, 14, 15, 16])

In [35]:
subset_sample_array[:]=1001
subset_sample_array

array([1001, 1001, 1001, 1001, 1001, 1001, 1001])

## Two-Dimensional array

In [22]:
import numpy as np

In [23]:
sample_matrix=np.array([[50,20,1,23],[24,23,21,33],[56,76,24,7]])
print(sample_matrix)

[[50 20  1 23]
 [24 23 21 33]
 [56 76 24  7]]


In [24]:
sample_matrix[1,2]

21

In [30]:
sample_matrix[2,:]

array([56, 76, 24,  7])

In [31]:
sample_matrix[2]

array([56, 76, 24,  7])

In [32]:
sample_matrix[:,(3,2)]

array([[23,  1],
       [33, 21],
       [ 7, 24]])

## Selection techniques

In [2]:
import numpy as np

In [3]:
sample_array=np.arange(1,20)
sample_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [5]:
sample_array+sample_array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38])

In [6]:
np.exp(sample_array)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05,
       4.42413392e+05, 1.20260428e+06, 3.26901737e+06, 8.88611052e+06,
       2.41549528e+07, 6.56599691e+07, 1.78482301e+08])

In [7]:
np.sqrt(sample_array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
       3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894])

In [8]:
np.log(sample_array)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
       2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898])

In [9]:
np.max(sample_array)

19

In [10]:
np.min(sample_array)

1

In [11]:
np.argmax(sample_array)

18

In [12]:
np.argmin(sample_array)

0

In [13]:
np.square(sample_array)

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196, 225, 256, 289, 324, 361])

In [14]:
np.std(sample_array)  //standard variance

5.477225575051661

In [15]:
np.var(sample_array)   //variance

30.0

In [16]:
np.mean(sample_array)

10.0

In [4]:
array=np.random.randn(3,4)
array

array([[-1.485525  , -0.13235382, -0.15019786,  0.32787418],
       [ 0.72014508, -0.93944388,  0.52379699, -0.50693131],
       [ 0.5072809 , -0.71175174, -1.4623938 ,  0.54647625]])

In [21]:
np.round(array,decimals=2)

array([[ 0.17, -0.02, -0.31,  0.19],
       [-1.02,  0.99, -1.63,  0.16],
       [-2.61,  0.57, -0.92, -0.61]])

In [22]:
sports=np.array(['golf','crircket','fball','cricket'])
np.unique(sports)

array(['cricket', 'crircket', 'fball', 'golf'], dtype='<U8')

In [2]:
import pandas as pd
import numpy as np

## Pandas dataframe and indexing

In [3]:
sports1=pd.Series([1,2,3,4],index=['cricket','football','basketball','golf'])
sports1

cricket       1
football      2
basketball    3
golf          4
dtype: int64

In [25]:
sports1['football']

2

In [26]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
print(sports2)

cricket     11
football     2
baseball     3
golf         4
dtype: int64


In [27]:
sports1+sports2

baseball       NaN
basketball     NaN
cricket       12.0
football       4.0
golf           8.0
dtype: float64

In [28]:
df1=pd.DataFrame(np.random.rand(8,5),index='A B C D E F G H'.split(),columns='Score1 Score2 Score3 Score4 Score5'.split())
print(df1)

     Score1    Score2    Score3    Score4    Score5
A  0.104486  0.372704  0.881021  0.521845  0.156780
B  0.294243  0.855287  0.555667  0.095857  0.122530
C  0.772213  0.597927  0.620913  0.992577  0.673299
D  0.565099  0.342526  0.980676  0.009897  0.907001
E  0.923679  0.531771  0.967373  0.285965  0.313609
F  0.198535  0.265523  0.939620  0.314545  0.489774
G  0.262756  0.419450  0.299055  0.306445  0.544661
H  0.579458  0.685317  0.653118  0.029124  0.617834


In [29]:
df1["Score1"]

A    0.104486
B    0.294243
C    0.772213
D    0.565099
E    0.923679
F    0.198535
G    0.262756
H    0.579458
Name: Score1, dtype: float64

In [32]:
df1[["Score1","Score2","Score3"]]

Score1    Score2    Score3
A  0.104486  0.372704  0.881021
B  0.294243  0.855287  0.555667
C  0.772213  0.597927  0.620913
D  0.565099  0.342526  0.980676
E  0.923679  0.531771  0.967373
F  0.198535  0.265523  0.939620
G  0.262756  0.419450  0.299055
H  0.579458  0.685317  0.653118

In [33]:
df1["Score6"]=df1["Score1"]+df1["Score2"]
print(df1)

     Score1    Score2    Score3    Score4    Score5    Score6
A  0.104486  0.372704  0.881021  0.521845  0.156780  0.477190
B  0.294243  0.855287  0.555667  0.095857  0.122530  1.149530
C  0.772213  0.597927  0.620913  0.992577  0.673299  1.370141
D  0.565099  0.342526  0.980676  0.009897  0.907001  0.907625
E  0.923679  0.531771  0.967373  0.285965  0.313609  1.455450
F  0.198535  0.265523  0.939620  0.314545  0.489774  0.464057
G  0.262756  0.419450  0.299055  0.306445  0.544661  0.682207
H  0.579458  0.685317  0.653118  0.029124  0.617834  1.264776


In [3]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[20,54,56,87,123]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [37]:
df["ID"]

0    101
1    102
2    103
3    107
4    176
Name: ID, dtype: object

In [38]:
df[["ID","Name","Profit"]]

ID   Name  Profit
0  101   John      20
1  102  Mercy      54
2  103  Akash      56
3  107  Kavin      87
4  176  Lally     123

In [4]:
df=df.drop("ID",axis=1)

In [5]:
df.drop(3)

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
4  Lally     123

In [6]:
df

Name  Profit
0   John      20
1  Mercy      54
2  Akash      56
3  Kavin      87
4  Lally     123